#!/usr/bin/env python3
"""

    COPYRIGHT (c) 2017 by FeatureMine Corporation.
    This software has been provided pursuant to a License Agreement
    containing restrictions on its use.  This software contains
    valuable trade secrets and proprietary information of
    FeatureMine Corporation and is protected by law.  It may not be
    copied or distributed in any form or medium, disclosed to third
    parties, reverse engineered or used in any manner not provided
    for in said License Agreement except with the prior written
    authorization from FeatureMine Corporation.

"""

"""
@package transport_writer_test
@author Andres Rangel
@date 10 Jul 2019
@brief File contains example and regression test for transport_writer tool usage.
"""

import argparse
from featuremine.tools.writer import TransportWriter
import extractor as extr
import os

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("id_file", help="Ids transport file")
    parser.add_argument("transact_file", help="Transactions transport file")
    parser.add_argument("pub_name", help="Desired publisher name")
    args = parser.parse_args()

    if os.path.exists(args.transact_file):
        os.remove(args.transact_file)

    tw = TransportWriter(args.id_file,args.transact_file,args.pub_name)

    #bod info
    tw.write_bod_info(300, 25700.36, imnt="A", account=103, time=1)
    tw.write_bod_info(400, 25700.55, imnt="AA", account=103, time=1)
    tw.write_bod_info(500, 25700.12, imnt="BA", account=103, time=1)

    #place
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=2)
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=2)
    tw.write_order_place(1001, 99.99, 200, 1, 3, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_placed(1001, 99.99, 200, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=3)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=3)
    tw.write_order_filled(1001, 99.99, 200, 0, imnt="A", venue="NYSE", account=101, time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", account=101, imnt="A", exdest="NYSE", time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", imnt="A", exdest="NYSE", entity="MAIN", time=3)

    #vwap
    tw.write_order_change(1002, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="AA", account=102, time=4)
    tw.write_order_change(1002, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="AA", entity="MAIN", time=4)
    tw.write_order_vwap(1002, 99.99, 10, 20, 200, 1, 3, 0.5, True, imnt="AA", venue="NYSE", account=102, time=4)
    tw.write_order_placed(1002, 99.99, 200, imnt="AA", venue="NYSE", account=102, time=4)
    tw.write_order_change(1002, 0, -9999.0, -100, 100, -9999.0, -100, 100, -9999.0, -100, 100, -9999.0, -100, 99.99, 0, 0, 0, "USD", imnt="AA", account=102, time=5)
    tw.write_order_change(1002, 0, -9999.0, -100, 100, -9999.0, -100, 100, -9999.0, -100, 100, -9999.0, -100, 99.99, 0, 0, 0, "USD", imnt="AA", entity="MAIN", time=5)
    tw.write_order_filled(1002, 99.99, 100, 0, imnt="AA", venue="NYSE", account=102, time=5)
    tw.write_trade_event(1002, 99.99, 9999.0, 0, 100, 0, "USD", account=102, imnt="AA", exdest="NYSE", time=5)
    tw.write_trade_event(1002, 99.99, 9999.0, 0, 100, 0, "USD", imnt="AA", exdest="NYSE", entity="MAIN", time=5)

    tw.write_trade_adjustment(9000.0, 1002, 90, 0, "USD", imnt="AA", account=102, time=6)
    tw.write_trade_adjustment(9000.0, 1002, 90, 0, "USD", imnt="AA", entity="MAIN", time=6)

    tw.write_order_change(1002,-1, -9999.0,-100, 100, -9999.0,-100, 100, -9999.0,-100, 100, -9999.0,-100, 99.99, 0, 0, 0, "USD", imnt="AA", account=102, time=6)
    tw.write_order_change(1002,-1, -9999.0,-100, 100, -9999.0,-100, 100, -9999.0,-100, 100, -9999.0,-100, 99.99, 0, 0, 0, "USD",imnt="AA", entity="MAIN", time=6)
    tw.write_order_filled(1002, 99.99, 100, 0, imnt="AA", venue="NYSE", account=102, time=6)
    tw.write_trade_event(1002, 99.99, 9999.0, 0, 100, 0, "USD", account=102, imnt="AA", exdest="NYSE", time=6)
    tw.write_trade_event(1002, 99.99, 9999.0, 0, 100, 0, "USD", imnt="AA", exdest="NYSE", entity="MAIN", time=6)

    #portfolio
    tw.write_order_change(1003, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=103, time=7)
    tw.write_order_change(1003, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=7)
    tw.write_order_portfolio(1003, 16, 99.99, 200, 1, 3, 0, imnt="A", venue="NYSE", account=103, time=7) #Begin
    tw.write_order_change(1004, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="AA", account=103, time=8)
    tw.write_order_change(1004, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="AA", entity="MAIN", time=8)
    tw.write_order_portfolio(1004, 16, 99.99, 200, 1, 3, 1, imnt="AA", venue="NYSE", account=103, time=8) #Body
    tw.write_order_change(1005, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="BA", account=103, time=9)
    tw.write_order_change(1005, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="BA", entity="MAIN", time=9)
    tw.write_order_portfolio(1005, 16, 99.99, 200, 1, 3, 2, imnt="BA", venue="NYSE", account=103, time=9) #End
    tw.write_order_placed(1003, 99.99, 200, imnt="A", venue="NYSE", account=103, time=10)
    tw.write_order_placed(1004, 99.99, 200, imnt="AA", venue="NYSE", account=103, time=10)
    tw.write_order_placed(1005, 99.99, 200, imnt="BA", venue="NYSE", account=103, time=10)
    tw.write_order_change(1003,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", account=103, time=11)
    tw.write_order_change(1003,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=11)
    tw.write_order_filled(1003, 99.99, 200, 0, imnt="A", venue="NYSE", account=103, time=11)
    tw.write_trade_event(1003, 99.99, 19998.0, 0, 200, 0, "USD", account=103, imnt="A", exdest="NYSE", time=11)
    tw.write_trade_event(1003, 99.99, 19998.0, 0, 200, 0, "USD", imnt="A", exdest="NYSE", entity="MAIN", time=11)
    tw.write_order_change(1004,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="AA", account=103, time=12)
    tw.write_order_change(1004,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="AA", entity="MAIN", time=12)
    tw.write_order_filled(1004, 99.99, 200, 0, imnt="AA", venue="NYSE", account=103, time=12)
    tw.write_trade_event(1004, 99.99, 19998.0, 0, 200, 0, "USD", account=103, imnt="AA", exdest="NYSE", time=12)
    tw.write_trade_event(1004, 99.99, 19998.0, 0, 200, 0, "USD", imnt="AA", exdest="NYSE", entity="MAIN", time=12)
    tw.write_order_change(1005,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="BA", account=103, time=13)
    tw.write_order_change(1005,-1, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 200, -19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="BA", entity="MAIN", time=13)
    tw.write_order_filled(1005, 99.99, 200, 0, imnt="BA", venue="NYSE", account=103, time=13)
    tw.write_trade_event(1005, 99.99, 19998.0, 0, 200, 0, "USD", account=103, imnt="BA", exdest="NYSE", time=13)
    tw.write_trade_event(1005, 99.99, 19998.0, 0, 200, 0, "USD", imnt="BA", exdest="NYSE", entity="MAIN", time=13)

    #hidden and rejected
    tw.write_order_change(1006, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=14)
    tw.write_order_change(1006, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=14)
    tw.write_order_hidden(1006, 99.99, 200, 1, 3, 0, imnt="A", venue="NYSE", account=101, time=14)
    tw.write_order_change(1006, -1, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=14)
    tw.write_order_change(1006, -1, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=14)
    tw.write_order_rejected(1006, imnt="A", venue="NYSE", account=101, time=14)

    #failed
    tw.write_order_change(1007, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=15)
    tw.write_order_change(1007, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=15)
    tw.write_order_place(1007, 99.99, 200, 1, 3, imnt="A", venue="NYSE", account=101, time=15)
    tw.write_order_change(1007, -1, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=15)
    tw.write_order_change(1007, -1, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 0, 19998.0, -200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=15)
    tw.write_order_failed(1007, imnt="A", venue="NYSE", account=101, time=15)

    #cancelation
    tw.write_order_change(1008, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=16)
    tw.write_order_change(1008, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=16)
    tw.write_order_place(1008, 99.99, 200, 1, 3, imnt="A", venue="NYSE", account=101, time=16)
    tw.write_order_placed(1008, 99.99, 200, imnt="A", venue="NYSE", account=101, time=16)
    tw.write_order_cancel(1008, imnt="A", venue="NYSE", account=101, time=17)
    tw.write_order_cancel_rej(1008, imnt="A", venue="NYSE", account=101, time=17)
    tw.write_order_change(1008,-1, -19998.0, 200, 0, -19998.0, 200, 0, -19998.0, 200, 0, -19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=18)
    tw.write_order_change(1008,-1, -19998.0, 200, 0, -19998.0, 200, 0, -19998.0, 200, 0, -19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=18)
    tw.write_order_canceled(1008, 200, imnt="A", venue="NYSE", account=101, time=17)

    #custom
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=2)
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=2)
    tw.write_order_custom(1001, 200, 1, 3, px=33.6, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_placed(1001, 99.99, 200, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=3)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=3)
    tw.write_order_filled(1001, 99.99, 200, 0, imnt="A", venue="NYSE", account=101, time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", account=101, imnt="A", exdest="NYSE", time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", imnt="A", exdest="NYSE", entity="MAIN", time=3)

    #custom marketable
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=2)
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=2)
    tw.write_order_custom(1001, 200, 1, 3, marketable=True, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_placed(1001, 99.99, 200, imnt="A", venue="NYSE", account=101, time=2)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=3)
    tw.write_order_change(1001,-1, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 200, -19998.0,-200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=3)
    tw.write_order_filled(1001, 99.99, 200, 0, imnt="A", venue="NYSE", account=101, time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", account=101, imnt="A", exdest="NYSE", time=3)
    tw.write_trade_event(1001, 99.99, 19998.0, 0, 200, 0, "USD", imnt="A", exdest="NYSE", entity="MAIN", time=3)

    #custom marketable
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=2)
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=2)
    tw.write_order_custom(1001, 200, 1, 3, marketable=True, imnt="A", venue="NONNYSE", account=101, time=2)

    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", account=101, time=2)
    tw.write_order_change(1001, 1, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 0, 19998.0, 200, 99.99, 0, 0, 0, "USD", imnt="A", entity="MAIN", time=2)
    tw.write_order_custom(1001, 200, 1, 3, marketable=True, imnt="A", venue="NONNYSE", account=101, time=2)

    extr.assert_base(args.transact_file, args.transact_file.replace(".test",".base"))
