name: CMake PR

on:
  pull_request:

permissions: write-all

jobs:
  utility:
    runs-on: ubuntu-20.04
    outputs:
      release-check: ${{ steps.release-check.outputs.release-check }}
    
    steps:
    - name: Utility tasks
      id: release-check
      uses: featuremine/actions/utility@main
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        utility_token: ${{ secrets.UTILITY_COMMIT_TOKEN }}

  build-manylinux:
    needs: utility
    runs-on: ubuntu-20.04
    container:
      image: public.ecr.aws/p0w8t0l8/ci-hosted-gh-centos7-gcc10.2.0
    
    steps:
    - uses: actions/checkout@v3

    - name: Build ${{ github.event.repository.name }} with fm gcc
      uses: featuremine/actions/package/build@main
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        cpack: TGZ
        docs: true
        upload: ${{ needs.utility.outputs.release-check == 'release' }}

  build-macos:
    needs: utility
    runs-on: macos-11

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: brew install pkg-config cmake googletest python doxygen

    - name: Install sphinx
      run: pip3 install sphinx breathe sphinx_rtd_theme m2r mistune==0.8.4 sphinx-autodoc-typehints

    - name: Build ${{ github.event.repository.name }} with fm gcc
      uses: featuremine/actions/package/build@main
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
