name: CMake

on:
  release:
    types: [prereleased]
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    env:
      CONTENT_TYPE_HEADER="Content-Type: application/zip"

    steps:
    - uses: actions/checkout@main
  
    - name: EnvTest
      run: echo "${{ secrets.GITHUB_TOKEN }} ${CONTENT_TYPE_HEADER}"

    - name: Upload
      run: curl -f -sSL -XPOST -H "Authorization:token ${GITHUB_TOKEN}" -H "${CONTENT_TYPE_HEADER}" --upload-file ${{github.workspace}}/build/yamal-7.2.6-Linux.deb https://uploads.github.com/repos/featuremine/yamal/releases/72552575/assets?name=yamal-7.2.6-Linux.deb
