name: CMake Pre-Release

on:
  pull_request:

permissions: write-all

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE: ${{ github.base_ref }}

jobs:

  rel_prep:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main  
    
    - name: Install PyGitHub
      run: pip3 install PyGithub
          
    - name: Check if PR is release
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{github.workspace}}/.github/workflows
      run: bash versioncheck.sh
      
  # runs only when the "release candidate" PR has been merged
  if_relPR_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - run: gh release edit v$(cat ../VERSION) --prerelease=false
