on:
  pull_request:
    # only runs when PR is being closed
    types:
      - closed
    # only runs when PR targets branch dev
    branches:
      - 'dev'
    # only runs when PR involves a change in the file named "VERSION"
    paths:
      - 'VERSION'

jobs:
  launch_rel_PR:
    # only runs when PR being closed has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: gh pr create --base main --head dev --title v$(cat VERSION)