name: CMake PR

on:
  pull_request:
    types: closed

permissions: write-all

jobs:

  check-release:
    runs-on: ubuntu-latest
    outputs:
      isRelease: ${{ steps.isRelease.outputs.release }}
    steps:
      
    - uses: actions/checkout@main
    
    - name: Install PyGitHub
      run: pip3 install PyGithub

    - name: Check if PR is release
      id: isRelease
      working-directory: ${{github.workspace}}/.github/workflows
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_MERGE_BASE: ${{ github.base_ref }}
        GIT_MERGE_COMMIT: ${{ github.sha }}
      run: python3 versioncheck


  publish-release:
    runs-on: ubuntu-latest
    needs: check-release    
    if: needs.check-release.outputs.isRelease == 'release' && github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@main
    
    - name: Publish
      run: gh release edit v$(cat VERSION) --draft=false
