name: Release Publication

on:
  pull_request:
    types: closed

permissions: write-all

jobs:

  check-draft:
    runs-on: ubuntu-latest
    outputs:
      draftExists: ${{ steps.draftExists.outputs.draft }}
    steps:
      
    - uses: actions/checkout@main
    
    - name: Install PyGitHub
      run: pip3 install PyGithub

    - name: Check if draft exists
      id: draftExists
      working-directory: ${{github.workspace}}/.github/workflows
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 draftcheck


  publish-release:
    runs-on: ubuntu-latest
    needs: check-draft    
    if: needs.check-draft.outputs.draftExists == 'true' && github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@main
    
    - name: Publish
      run: gh release edit v$(cat VERSION) --draft=false
