# COPYRIGHT (c) 2019-2023 by Featuremine Corporation.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Release Publication

on:
  pull_request:
    types: closed

permissions: write-all

jobs:
  publish-release:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Publish release
      uses: featuremine/actions/release@v2
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
